### ISSUE TITLE
extremely slow emulation speed after update to 1.5.1

### ISSUE THREAD

**Issue by STLITGuy** [WilliamLCobb/iNDS#101] opened 2016-04-23 02:33 UTC
I built out 1.5.1 and the speed is really slow I get about 12 FPS.  Prior to that I was able to play at normal speed without issue.  It also crashes a lot more frequently.  I did attempt to change to to a video filter but that made it even worse so I turned that off but it's still not at normal speed.  I tried a few games all are slow.  Attached is a game save that highlights the issue.

Device is an iPhone 6 Plus.

[1456 - Legend of Zelda - Phantom Hourglass, The (U)(Independent).Save 1.zip](https://github.com/WilliamLCobb/iNDS/files/232771/1456.-.Legend.of.Zelda.-.Phantom.Hourglass.The.U.Independent.Save.1.zip)

**Comment by iOSSOi** [comment] 2016-04-23 03:15
Could you pretty please upload the ipa/deb to dropbox or Google drive, please. Would be highly appreciated!

**Comment by STLITGuy** [comment] 2016-04-23 03:48
I self signed the build I'm using in Xcode since I don't have a jailbroken device. You can do the same thing just download Xcode sign up for a free developer account then download the source from github. 

Here are the basic steps
http://www.idownloadblog.com/2015/09/18/how-to-compile-apps-using-xcode-7-to-run-on-a-non-jailbroken-device/

Use this URL for iNDS
https://github.com/WilliamLCobb/iNDS

**Comment by iOSSOi** [comment] 2016-04-23 07:04
The problem is that im in the hospital now for chemotherapy, there is no way for me to compile anything. Even  if I was home I wouldn't be able to compile them in later because I don't have an OS X machine.  At the moment I am using zeusmos and iPwnstore  to  sign and install apps on my ipad without using xcode. Please,  i beg of you, or anyone else that has the possibility to send me an ipa or deb with the latest versions.  Sorry for sounding like a five-year-old but I really don't have any other chance to download and compile the files myself when at the hospital

**Comment by WilliamLCobb** [comment] 2016-04-23 16:41
Definitely man. Let me work on it a little bit today and get the fps stable because it's still pretty laggy. I'll post a link to the ipa here after

**Comment by WilliamLCobb** [comment] 2016-04-23 16:43
Also the crashing is because I was fumbling around with the code trying to fix the soul silver black screen. That's weird the fps was low even with no filter on

**Comment by WilliamLCobb** [comment] 2016-04-23 21:52
iNDS 1.5.1b1 www.williamlcobb.com/iNDS/iNDS-1-5-1b1.ipa

Should fix the fps issue but there are a few graphical issues

**Comment by iOSSOi** [comment] 2016-04-23 22:15
Thank you!! Im so happy to see you working so hard on the emulator again. I would like to gift you my first gen NDS if it would be any help for further development of inds.  You don't have to see it as a donation, it's more like if you would need it to solve any graphical or speed  Problems. Intrested?  Or should I just keep quiet and enjoy the amazing work you are already doing with the emulator?

**Comment by DarknesGaming** [comment] 2016-04-25 13:08
iNDS 1.5.1 is really laggy? I guess I better not update. Plus, I don't have my PC to even try to compile this code.
@WilliamLCobb iNDS seems to be suffering from gpSPhone's 8.4 problem. I hated gpSPhone 8.4 because it had terrible performance issues, but 8.4.1 patched that. It can't be too hard to fix the whole performance thing, right?
@STLITGuy what device are you using? If it's an old one, expect slow speeds from Phantom Hourglass. If it's a new one, then this is a problem we must address immediately.

**Comment by WilliamLCobb** [comment] 2016-04-25 18:17
The filter was not running in parallel with the core causing a slowdown. This should be fixed

**Closed by WilliamLCobb** 2016-04-25 18:17 UTC
