### ISSUE TITLE
Microphone support

### ISSUE THREAD

**Issue by illando** [WilliamLCobb/iNDS#63] opened 2016-01-17 09:49 UTC
Is microphone already supportey? It could be useful on game like WarioWare:Touched!
Microphone is currently supporterted by the Mac version of DeSmuME.

**Comment by pmp174** [comment] 2016-01-17 12:31
This is a duplicate of #23 . If you need to know anything ask questions on that issue.

**Comment by illando** [comment] 2016-01-17 13:12
I'm sorry, next time I'll check better! :)

**Closed** 2016-01-17 13:15 UTC
