### ISSUE TITLE
Crash after clicking on iNDS app

### ISSUE THREAD

**Issue by edoelghzaly254** [WilliamLCobb/iNDS#60] opened 2016-01-15 11:49 UTC
iPhone 6
iOS 9.2
Non-jailbroken
iNDS downloaded from iOSEmus
I can't remember remember the version, but I downloaded the app week ago. 

Problem:
So the application was working perfectly until today, I wanted to download Megaman Battle Network 5 from emuparadise, and once it finished download on safari, I clicked open in iNDS, then the app just got frozen for more than 5 minutes. So I restarted the phone and when I wanted to check the app, it was crashing everytime I click on it. I don't know what happened, it was working perfectly when I was playing Digimon World Dawn.

**Comment by hector0406** [comment] 2016-01-16 17:26
Let me quote what user "pmp174" said in other thread about this:

This is most likely being caused by an expired signature and is not an INDS issue. If you want look for someone who can build you a copy of INDS or get a buildstore account. The developer of INDS does not distribute iemulator versions of the app. You might be able to find a resource here https://github.com/WilliamLCobb/iNDS/wiki/Building-INDS-for-Jailed-iDevices

**Comment by edoelghzaly254** [comment] 2016-01-16 20:04
Uhh.. I think these steps that are mentioned in the link is kind of tough for me to understand. But I'd appreciate any kind of help regarding builiding a copy for iNDS.

**Comment by pmp174** [comment] 2016-01-16 20:11
Do you have a mac?

**Comment by hector0406** [comment] 2016-01-16 20:40
There are a lot of tutorials for you to get iNDS working on your apple device. However, if you still think it's confusing, the easier way (at least what I recommend) is getting a account from sites like BuildStore or iPwnStore. Their cost: $10 annually.

BuildStore link: http://builds.io

iPwnStore link: https://ipwnstore.me

**Comment by pmp174** [comment] 2016-01-16 20:50
If you want give me your email and I will send you a version within an hour .

**Comment by edoelghzaly254** [comment] 2016-01-17 06:27
Thank you, here is my e-mail: edoelghzy254@yahoo.com
And if the e-mail you're gonna send is gonna include steps, please use screenshots to make it easy for me ti understand.

**Comment by edoelghzaly254** [comment] 2016-01-17 06:28
I'd buy an account, hector0406, but I'm in a country that forces me to have a bank account with 30k+ cash so I could have a Visa.

**Comment by pmp174** [comment] 2016-01-17 12:38
I have sent you an IPA , you should close this issue now.

**Comment by edoelghzaly254** [comment] 2016-01-17 13:56
I haven't recieved anything. 
Try this one: edoelghzaly@yahoo.com

**Comment by edoelghzaly254** [comment] 2016-01-17 13:59
I'm sorry, pmp174. I have typed the first e-mail wrongly. This should be the correct one: edoelghzaly254@yahoo.com

**Comment by pmp174** [comment] 2016-01-17 17:36
Its sent please close this issue.

**Closed** 2016-01-17 18:25 UTC

**Comment by chatsann** [comment] 2016-07-01 02:52
Hi everyone,
iPhone 6+
iOS 9.3.2
Non-jailbroken

# The problem is
INDS was crashed yesterday So I restarted the phone and when I wanted to check the app, it was crashing every time I click on it. I don't know what happened, it was working perfectly when I was playing Pokemon Platinum So what can I do? Who can suggestme
my email is chatsann@gmail.com
Thanks for your support.

**Comment by essiw** [comment] 2016-07-02 15:48
You are probably using iemulators as a source, which has a revoked certificate, either use a different source or wait for them to fix. Not a problem with the app.

**Comment by chatsann** [comment] 2016-07-03 09:38
Thanks for your information. So I want to play Pokemon how can I do?? or
the only way is to wait for new certificate please advise.

2016-07-02 22:48 GMT+07:00 essiw <notifications@github.com>:

**Comment by essiw** [comment] 2016-07-03 09:40
As I said, you can use an other source. You can build the app directly from github (see wiki) or download it from builds.io (costs money per year) and there are other options as well.

**Comment by essiw** [comment] 2016-07-03 15:29
See the wiki linked at the top of this page.

**Comment by chatsann** [comment] 2016-07-04 02:25
Thanks a lot
By the way do you know about how long for the new certificate for INDS?

2016-07-03 22:29 GMT+07:00 essiw <notifications@github.com>:

**Comment by essiw** [comment] 2016-07-04 06:30
No, you will have to ask that to iemulators

**Comment by chatsann** [comment] 2016-07-04 07:41
Oh I see. Thanks
But if I use the build store I will pay for account per year right?

2016-07-04 13:30 GMT+07:00 essiw <notifications@github.com>:

**Comment by essiw** [comment] 2016-07-04 08:13
yes

**Comment by chatsann** [comment] 2016-07-04 09:52
OK
Thank you so much @essiw
I think I will wait for the new certificate.

2016-07-04 15:13 GMT+07:00 essiw <notifications@github.com>:
